name: vynilmatic
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text:
  built_collection: ^5.0.0
  built_value: ^8.0.6
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.4.0
  font_awesome_flutter:
  google_fonts: ^2.1.0
  intl:
  json_serializable: ^4.0.1
  page_transition:
  share_plus: ^2.1.4

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^1.11.5
  built_value_generator: ^8.0.4
  flutter_launcher_icons: ^0.9.1

  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_launcher_icon.png'


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/


